kind: "Deployment"
apiVersion: "apps/v1"
metadata:
  name: calculator
  namespace: bsamal-dev
  labels:
    app: calc
spec:
  selector:
    matchLabels:
      app: calc
  template: 
    metadata:
      labels:
        app: calc
    spec:
      containers:
        - name: calculator
          image: image-registry.openshift-image-registry.svc:5000/bsamal-dev/calc
          ports:
            - containerPort: 8080
              protocol: "TCP"
  replicas: 2 
  strategy: 
    type: RollingUpdate
  revisionHistoryLimit: 2 
  minReadySeconds: 0 
